---
name: C++ / Test

on: # yamllint disable-line rule:truthy
  pull_request:
    branches: ["main"]
  push:
    branches: ["main"]

jobs:
  test:
    name: Bazel Test (C++)
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run C++ tests via Bazel
        run: |
          bazel test --test_tag_filters=cc //problems/...
